server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://server:3001/;
        proxy_set_header Host $host;
        client_max_body_size 100M;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
